<a href="https://colab.research.google.com/github/mishapyt74/DataScience/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

vector1 = np.arange(1, 11)
vector1



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
matrix1 = np.zeros((3, 3))
matrix1


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
matrix2 = np.random.randint(1, 11, size=(5, 5))
matrix2


array([[ 4,  3,  3,  1,  5],
       [ 5, 10,  9,  2,  6],
       [ 7,  1,  3,  6,  4],
       [ 8,  6,  7,  8,  9],
       [ 9,  3,  7,  1,  4]])

In [10]:
matrix2 = np.random.randint(1, 11, size=(5, 5))
matrix2


array([[ 3, 10, 10,  3, 10],
       [ 5,  5,  6,  1,  1],
       [ 2,  4,  9,  4,  4],
       [ 8,  1,  5, 10,  5],
       [ 5,  8,  4,  5, 10]])

In [11]:
matrix3 = np.random.rand(4, 4)
matrix3


array([[0.04584498, 0.66121547, 0.04957584, 0.32026858],
       [0.15486768, 0.5093175 , 0.2456764 , 0.81721462],
       [0.83999067, 0.12192169, 0.79973473, 0.1744746 ],
       [0.05586523, 0.10298771, 0.76385889, 0.3662943 ]])

In [12]:
vector2 = np.random.randint(1, 11, size=5)
vector2


array([9, 6, 2, 9, 9])

In [13]:
vector3 = np.random.randint(1, 11, size=5)
vector3

array([5, 5, 6, 5, 7])

In [14]:
vector4 = np.random.randint(1, 11, size=4)
vector4

array([7, 5, 2, 4])

In [15]:
vector5 = np.random.rand(3)
vector5

array([0.45752448, 0.96310931, 0.86619162])

In [16]:
vector6 = np.random.randint(1, 51, size=4)
vector6

array([15, 17, 24, 21])

In [17]:
scalar = np.dot(vector2, vector3)
scalar


195

In [18]:
matrix4 = np.random.randint(1, 11, size=(2, 2))
matrix5 = np.random.randint(1, 11, size=(2, 3))


In [19]:
product = np.dot(matrix4, matrix5)
product


array([[118, 116,  84],
       [ 98, 100,  72]])

In [20]:
product = np.dot(matrix4, matrix5)
product


array([[118, 116,  84],
       [ 98, 100,  72]])

In [21]:
matrix6 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix6)
inverse_matrix


array([[-1.33333333, -1.16666667,  2.16666667],
       [ 6.        ,  4.5       , -8.5       ],
       [-3.        , -2.        ,  4.        ]])

In [22]:
matrix7 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix7)
transposed_matrix


array([[0.10940065, 0.17684626, 0.49562902, 0.70339581],
       [0.26523004, 0.95364027, 0.5962733 , 0.40789163],
       [0.53077661, 0.38967367, 0.94286503, 0.28602428],
       [0.05178408, 0.40198526, 0.45320814, 0.06828221]])

In [23]:
matrix8 = np.random.randint(1, 11, size=(3, 4))
result_vector = np.dot(matrix8, vector4)
result_vector


array([113,  77,  57])

In [24]:
matrix9 = np.random.rand(2, 3)
result_vector2 = np.dot(matrix9, vector5)
result_vector2


array([1.03697257, 1.18767453])

In [25]:
matrix10 = np.random.randint(1, 11, size=(2, 2))
matrix11 = np.random.randint(1, 11, size=(2, 2))
elementwise_product = np.multiply(matrix10, matrix11)
elementwise_product


array([[56, 10],
       [40,  2]])

In [26]:
product_matrix = np.dot(matrix10, matrix11)
product_matrix


array([[61, 82],
       [61, 82]])

In [27]:
matrix12 = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix12)
sum_of_elements


1267

In [28]:
matrix13 = np.random.randint(1, 11, size=(4, 4))
matrix14 = np.random.randint(1, 11, size=(4, 4))
difference_matrix = np.subtract(matrix13, matrix14)
difference_matrix


array([[ 6,  5, -6, -3],
       [-1,  2,  1, -6],
       [-4,  2, -1,  3],
       [ 6,  9,  5,  6]])

In [29]:
row_sum_vector = np.sum(matrix12, axis=1)
row_sum_vector


array([231, 246, 157, 274, 359])

In [30]:
matrix15 = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix15)
squared_matrix


array([[ 4, 36, 25,  9],
       [36,  4, 64, 49],
       [49, 25, 49,  1]])

In [31]:
square_root_vector = np.sqrt(vector6)
square_root_vector


array([3.87298335, 4.12310563, 4.89897949, 4.58257569])